[package]
name = "cuckoo"
version = "0.1.0"
edition = "2021"

[lib]
name = "cuckoo_hash"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.18", features = ["extension-module"] }
rand = "0.8.5"
xxhash-rust = { version = "0.8", features = ["xxh32", "xxh64"] }

